# forgot window
forgot_password_window = Window(app, title="Forgot password", bg = "white", height="650")
forgot_password_window.tk.resizable(False, False)
space = Text(forgot_password_window, text = "", size="5")
picture = Picture(forgot_password_window, image="logo.png", width = 120, height = 120)
forgot_pass_username = Text(forgot_password_window, text = "Enter Your Username:")
space = Text(forgot_password_window, text = "", size="2")
forgot_pass_user = TextBox(forgot_password_window, width="23")
forgot_pass_title = Text(forgot_password_window, text = "Enter Your New Password:")
space = Text(forgot_password_window, text = "", size="2")
new_forgot_pass = TextBox(forgot_password_window, width="23", hide_text = True)
space = Text(forgot_password_window, text = "", size="20")
submit = PushButton(forgot_password_window, text = "Submit", command=password_reset_window, width="17")
space = Text(forgot_password_window, text = "", size="2")
space = Text(forgot_password_window, text = "", size="2")
back_button2 = PushButton(forgot_password_window, text = "Back", command=go_back_main, width="17")
forgot_password_window.hide()
