# Register window
sign_up_window = Window(app, title="Register Page", bg = "white", height="650")
picture = Picture(sign_up_window, image="logo.png", width = 80, height = 80)
sign_up_window.tk.resizable(False, False)
space = Text(sign_up_window, text = "", size="5")
sign_up_name = Text(sign_up_window, text = "Enter your first name:")
space = Text(sign_up_window, text = "", size="5")
name_box = TextBox(sign_up_window, width="23")
space = Text(sign_up_window, text = "", size="5")
sign_up_surname = Text(sign_up_window, text = "Enter your surname:")
space = Text(sign_up_window, text = "", size="5")
surname_box = TextBox(sign_up_window, width="23")
space = Text(sign_up_window, text = "", size="5")
sign_up_username = Text(sign_up_window, text = "Enter your username:")
space = Text(sign_up_window, text = "", size="5")
username_box = TextBox(sign_up_window, width="23")
space = Text(sign_up_window, text = "", size="5")
sign_up_password = Text(sign_up_window, text = "Enter your password:")
space = Text(sign_up_window, text = "", size="5")
password_box = TextBox(sign_up_window, width="23", hide_text = True)
space = Text(sign_up_window, text = "", size="5")
sign_up_password_confirm = Text(sign_up_window, text = "Confirm your password:")
space = Text(sign_up_window, text = "", size="5")
password_box_confirm = TextBox(sign_up_window, width="23", hide_text = True)
space = Text(sign_up_window, text = "", size="5")
cookies = CheckBox(sign_up_window, command=cookies, text="Accept cookie policy")
terms = CheckBox(sign_up_window, command=terms, text="Accept terms and conditions")
cookies.tk.config(cursor="hand2")
space = Text(sign_up_window, text = "", size="10")
submit = PushButton(sign_up_window, text = "Submit", command=register, width="17")
space = Text(sign_up_window, text = "", size="5")
back_button = PushButton(sign_up_window, text = "Back", command=go_back_main, width="17")
sign_up_window.hide()
