# settings window
settings_window = Window(app, title="Settings.",bg = "white", height="760", width="1100")
settings_window .tk.resizable(False, False)
box = Box(settings_window, align="top", width="fill", layout="grid", border=True)
picture = Picture(box, image="logo.png",height=80, width=80, align="left", grid=[0, 1])
space = Text(box, text = "", width="10", grid=[1, 1])
book = PushButton(box, text="Book", command=booking, grid=[2, 1], height="3", width=20)
view_booking_settings = PushButton(box, text="View Bookings", command=booking_view, grid=[3, 1], height="3", width=20)
settings2 = PushButton(box, text="Settings", grid=[4, 1], height="3", width=20)
space = Text(box, text = "", width="5", grid=[5, 1])
log_out = PushButton(box, text="Log Out", command=go_back_main, grid=[6, 1], height="3", width=20)
space = Text(landing_page_window, text = "", size="10")
settings_message = Text(settings_window, text = "Settings Homepage", color="#2596be", font="bold")
settings_message.tk.config(font=("Ariel", 16, "bold", "underline"))
space = Text(settings_window, text = "", size="20")
mode_title = Text(settings_window, text = "Dark mode or light mode.", color="#2596be")
mode_title.tk.config(font=("Ariel", 16, "bold"))
space = Text(settings_window, text = "", size="5")
DarkModeButton = PushButton(settings_window, text="Dark Mode", width=27, command=DarkMode)
space = Text(settings_window, text = "", size="5")
LightModeButton = PushButton(settings_window, text="Light Mode", width=27, command=LightMode)
space = Text(settings_window, text = "", size="5")
mode_title = Text(settings_window, text = "Font Settings.", color="#2596be")
mode_title.tk.config(font=("Ariel", 16, "bold"))
space = Text(settings_window, text = "", size="5")
font = Combo(settings_window, options=["courier", "times new roman", "verdana", "Ariel"], command=change_font)
space = Text(settings_window, text = "", size="5")
slider = Combo(settings_window,options= ["8", "9", "10", "11", "12"], command=change_font_size)
space = Text(settings_window, text = "", size="5")
mode_title = Text(settings_window, text = "Change password.", color="#2596be")
mode_title.tk.config(font=("Ariel", 16, "bold"))
space = Text(settings_window, text = "", size="5")
new_password_box = TextBox(settings_window, width="23", hide_text = True)
space = Text(settings_window, text = "", size="5")
submit_settings = PushButton(settings_window, text = "Submit", command=password_reset, width="17")
box3 = Box(settings_window, align="bottom", width="fill", layout="grid", border=True)
space = Text(box3, text = "", width="40", grid=[0, 1])
footer_logo = Picture(box3, image="logo.png",height=50, width=50, align="left", grid=[1, 1])
copyright = Text(box3, text = "Copyright © Booker 2023", color="#2596be", grid=[2, 1])
back_button2 = PushButton(box3, text = "Back", command=go_back_landing, width="17",grid=[3, 1], align="right")
settings_window.hide()
